name: Prettier
on: [push]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
      - run: npm run format
